public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        System.out.println("Задача 2");
        dog = dog+4;
        System.out.println(dog);
        cat =cat+4;
        System.out.println(cat);
        paper=paper+4;
        System.out.println(paper);
        System.out.println("Задача 3");
        dog = dog-3.5;
        System.out.println(dog);
        cat =cat-1.6;
        System.out.println(cat);
        paper=paper-7639;
        System.out.println(paper);
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend=friend/7;
        System.out.println(friend);
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog /3.5;
        System.out.println(frog);
        frog = frog +4;
        System.out.println(frog);
        System.out.println("Задача 6");
        var boxerWeight1 = 78.2;
        var boxerwWeight2 = 82.7;
        var totalWeight = boxerWeight1 + boxerwWeight2;
        System.out.println(totalWeight);
        var differenceMass = boxerWeight1-boxerwWeight2;
        System.out.println(differenceMass);
        System.out.println("Задача 7");
        var remains= boxerwWeight2  % boxerWeight1;
        System.out.println(remains);
        System.out.println("Задача 8");
        var totalHours=640;
        var time=8;
        var staff=totalHours/time;
        System.out.println("Всего работников в компании —  " +staff+ "  человек");
        var  staff2=staff+94;
        var time2 =staff2*time;
        System.out.println("Если в компании работает " + staff2 +"  человек,то всего " + time2 + "  часов работы может быть поделено между сотрудниками");
    }
}